using System;
using System.Globalization;
using UnityEngine;
using System.Threading;
using Reactional.Playback;
using UnityEditor;

namespace Reactional.Core
{
    [RequireComponent(typeof(AudioSource))]
    [DefaultExecutionOrder(1000)]
    public class ReactionalEngine : MonoBehaviour
    {
        public static ReactionalEngine Instance { get; private set; }

        public Engine engine;
        [HideInInspector] public bool _allowPlay;
        public bool _outputEvents = true;
        private int _sampleRate;
        private float tempo_bpm;
        private int tempo_microbeats;
        private float currentBeat;
        private int _currentRootNote;
        private float[] _currentScale;
        private int[] _currentBarBeat = new int[2];
        public float TempoBpm => tempo_bpm;
        public float CurrentBeat => currentBeat;
        public int CurrentRootNote => _currentRootNote;
        public float[] CurrentScale => _currentScale;
        public int[] CurrentBarBeat => _currentBarBeat;

        private int _resample_quality = 2;

        public int ResampleQuality
        {
            get => _resample_quality;
            set => _resample_quality = value;
        }

        private bool _AudioUpdateMode = false;
        private bool _threadedUpdateMode = true;
        private int _beatIndex = 3;
        [HideInInspector] public AudioSource output;
        
        [Tooltip("Enable logging for Reactional system")]
        [SerializeField]
        internal LogLevel _logLevel = (LogLevel.Log | LogLevel.Warning | LogLevel.Error);
        public static LogLevel LogLevel
        {
            get => (LogLevel)PlayerPrefs.GetInt("Reactional.LogLevel", (int)(LogLevel.Log | LogLevel.Warning | LogLevel.Error));
            set
            {
                if(Instance) Instance._logLevel = value;
                PlayerPrefs.SetInt("Reactional.LogLevel", (int)value);
            } 
        }
        
        #region Delegates

        public delegate void NoteOnEvent(double offset, int sink, int lane, float pitch, float velocity);

        public delegate void NoteOffEvent(double offset, int sink, int lane, float pitch, float velocity);

        public delegate void StingerEvent(double offset, bool startevent, int stingerOrigin);

        public delegate void AudioPlayEvent();
        
        public delegate void AudioEndEvent();

        public delegate void BarBeatEvent(double offset, int bar, int beat);
        
        public delegate void QuantizationEvent();

        #endregion

        #region Events

        OSCMessage[] events;
        public NoteOnEvent onNoteOn;
        public NoteOffEvent onNoteOff;
        public StingerEvent stingerEvent;
        public AudioPlayEvent onAudioPlay;
        public AudioEndEvent onAudioEnd;
        public BarBeatEvent onBarBeat;
        
        public struct QuantizationEventData
        {
            public QuantizationEvent Event;
            public int LastQuant;
        }
        private const int QUANT_EVENT_COUNT = 15;
        public readonly QuantizationEventData[] quantization_events = new QuantizationEventData[QUANT_EVENT_COUNT];

        #endregion

        [SerializeField] private Reactional.Setup.UpdateMode _updateMode = Reactional.Setup.UpdateMode.Threaded;

        public Reactional.Setup.UpdateMode UpdateMode
        {
            get => _updateMode;
            set => _updateMode = value;
        }

        [SerializeField] public Reactional.Setup.AudioOutputMode _audioOutputMode = Reactional.Setup.AudioOutputMode.Unity;

        public Reactional.Setup.AudioOutputMode AudioOutputMode
        {
            get => _audioOutputMode;
            set => _audioOutputMode = value;
        }

        void Awake()
        {
            using var _ = ProfilerMarkers.k_MemoryManagement.Auto();
            
            engine = new Engine();            
            if (_audioOutputMode == Reactional.Setup.AudioOutputMode.Unity)
                _sampleRate = AudioSettings.outputSampleRate;
            output = GetComponent<AudioSource>();

            if (!Instance)
                Instance = this;
        }

        private Thread thread;

        void Start()
        {
            switch (_updateMode)
            {
                case Reactional.Setup.UpdateMode.Threaded:
                    _threadedUpdateMode = true;
                    _AudioUpdateMode = false;
                    break;
                case Reactional.Setup.UpdateMode.AudioThread:
                    _threadedUpdateMode = false;
                    _AudioUpdateMode = true;
                    break;
                case Reactional.Setup.UpdateMode.Main:
                    _threadedUpdateMode = false;
                    _AudioUpdateMode = false;
                    break;
                default:
                    break;
            }

            if (_threadedUpdateMode)
            {
                _AudioUpdateMode = false;
                thread = new Thread(DoWork);
                thread.Start();
            }
        }

        void DoWork()
        {
            while (true)
            {
                if (_allowPlay)
                    Process();
                Thread.Sleep(16); // 60fps
            }
        }

        void OnDestroy()
        {
            using var _ = ProfilerMarkers.k_ResourceCleanup.Auto();
            
            if (thread != null && thread.IsAlive)
                thread.Abort();
        }

        private void Update()
        {
            if (engine == null || !_allowPlay) return;
            if (Playback.Playlist.IsPlaying)
                GetEvents(0);
            if (Playback.Theme.IsPlaying)
                GetEvents(1);            
            if (!_AudioUpdateMode && !_threadedUpdateMode) Process();
        }

        void OnAudioFilterRead(float[] data, int channels)
        {
            if (_audioOutputMode != 0)
            {
                return;
            }
            
            int frames = data.Length / channels;
            if (_allowPlay && engine != null)
            {
                ProfilerMarkers.k_AudioFilterRead.Begin();
                engine.RenderInterleaved(_sampleRate, frames, channels, data);
                ProfilerMarkers.k_AudioFilterRead.End();
                
                if (_AudioUpdateMode && !_threadedUpdateMode) Process();
            }
        }

        private void Process()
        {
            using var _ = ProfilerMarkers.k_EngineUpdate.Auto();
            engine.Process(-1);
            int id = Instance.engine.GetTheme() < 0
                ? Instance.engine.GetTrack()
                : Instance.engine.GetTheme();
            if (id >= 0)
            {
                currentBeat = (float)engine.GetParameterFloat(id, _beatIndex) / 1_000_000f;
                tempo_bpm = (float)engine.GetParameterFloat(id, engine.FindParameter(id, "bpm"));
            }
        }

        private void OnEnable()
        {
            onNoteOn += RouteNoteOn;
            onNoteOff += RouteNoteOff;
            stingerEvent += RouteStingerEvent;
            onBarBeat += RouteBarBeat;
        }

        private void OnDisable()
        {
            onNoteOn -= RouteNoteOn;
            onNoteOff -= RouteNoteOff;
            stingerEvent -= RouteStingerEvent;
            onBarBeat -= RouteBarBeat;
            _allowPlay = false;
        }

        private void GetEvents(int trackid)
        {
            /* REACTIONAL OSC EVENTS
             *
             * We can easily intercept the events generated from the reactional system by polling from the OSC queue.
             * Reactional uses communication via the OSC protocol between internal subsystems.
             * This has an added benefit in that we can listen in on said communication, and also communicate directly
             * with the various features, as a sort of low level API.
             *
             * The most common use case would be to listen for "noteon", and "noteoff" messages generated by the engine.
             */

            using var _ = ProfilerMarkers.k_EventProcessing.Auto();
            
            if (!_outputEvents) return;
            bool gotScale = false, gotRoot = false, gotBar = false;
            long startBeat = 0;
            var numMessages = engine.PollBegin(ref startBeat);
            if (numMessages < 0)
            {
                Setup.ReactionalLog(Native.reactional_string_error(numMessages), LogLevel.Warning);
            }
            events = engine.PollTarget(trackid, numMessages);
            var len = events?.Length ?? -1;
            for (int i = 0; i < len; i++)
            {
                OSCMessage val = events![i];
                switch (val.Address)
                {
                    case "/noteon":
                        onNoteOn?.Invoke(
                            offset: (long)val[0] / 1_000_000.0d, // 0    h microbeats
                            sink: (int)val[1], // 1    i sink index  (a sink is the origin of the events)
                            lane: (int)val[2], // 2    i output/group index
                            pitch: (float)val[3], // 3    f pitch
                            velocity: (float)val[4] // 4    f velocity 
                        );
                        break;

                    case "/noteof":
                        onNoteOff?.Invoke(
                            offset: (long)val[0] / 1_000_000.0d, // 0    h microbeats
                            sink: (int)val[1], // 1    i sink index  (a sink is the origin of the events)
                            lane: (int)val[2], // 2    i output/group index
                            pitch: (float)val[3], // 3    f pitch
                            velocity: (float)val[4] // 4    f velocity 
                        );
                        break;

                    case "/audio/play":
                        onAudioPlay?.Invoke();
                        break;

                    case "/audio/end":
                        onAudioEnd?.Invoke();
                        break;

                    case "/scale":
                        if ((trackid == 1 && Playback.Playlist.IsPlaying) || gotScale)
                            continue;
                        string scale = (string)val[4];
                        string[] scaleArray = scale.Split(' ');
                        _currentScale = new float[scaleArray.Length - 1];
                        for (int j = 0; j < scaleArray.Length - 1; j++)
                        {
                            _currentScale[j] = float.Parse(scaleArray[j + 1], CultureInfo.InvariantCulture);
                        }
                        gotScale = true;
                        break;

                    case "/root":
                        if ((trackid == 1 && Playback.Playlist.IsPlaying) || gotRoot)
                            continue;

                        _currentRootNote = (int)(float)val[3];
                        gotRoot = true;
                        break;

                    case "/bar":
                        if (gotBar)
                            continue;

                        onBarBeat?.Invoke(
                            offset: ((long)(val[0]) / 1_000_000.0d), // 0    h microbeats
                            bar: (int)(val[3]), // 3    i bar
                            beat: (int)(val[4]) // 4    i beat
                        );
                        _currentBarBeat[0] = (int)val[3];
                        _currentBarBeat[1] = (int)val[4];
                        gotBar = true;

                        break;

                    case "/stinger/start":
                        stingerEvent?.Invoke(
                            offset: ((long)(val[0]) / 1_000_000.0d), // 0    h microbeats
                            startevent: true,
                            stingerOrigin: (int)(val[3]) // 3    i stinger origin
                        );
                        break;

                    case "/stinger/stop":
                        stingerEvent?.Invoke(
                            offset: ((long)(val[0]) / 1_000_000.0d), // 0    h microbeats
                            startevent: false,
                            stingerOrigin: (int)(val[3]) // 3    i stinger origin
                        );
                        break;
                    default:
                        break;
                }
            }
            events = null;
            var end = engine.PollEnd(numMessages);
            if (end < 0)
            {
                Setup.ReactionalLog(Native.reactional_string_error(end), LogLevel.Warning);
            }

            var microbeat = MusicSystem.GetCurrentMicroBeat();
            if (microbeat < 0) { return; }
            for (var i = 0; i < QUANT_EVENT_COUNT; i++)
            {
                ref var quantizationEventData = ref quantization_events[i];
                ref var quantEvent = ref quantizationEventData.Event;
                ref var lastQuant = ref quantizationEventData.LastQuant;

                if (quantEvent == null) { continue; }
                var quant = MusicSystem.QuantToDouble((MusicSystem.Quant)i) * 1_000_000;
                if (lastQuant > microbeat && microbeat > 0) { lastQuant = (int)(Mathf.Ceil((float)(microbeat / quant)) * quant); }
                if (lastQuant <= 0) { lastQuant = (int)(Mathf.CeilToInt((float)(microbeat / quant)) * quant); continue; }
                if (microbeat >= lastQuant)
                {
                    lastQuant = (int)(Mathf.CeilToInt((float)(microbeat / quant)) * quant);
                    quantEvent.Invoke();
                }
            }
        }

        #region Event Handlers

        private void RouteNoteOn(double beat, int sink, int lane, float pitch, float velocity)
        {
        }

        private void RouteNoteOff(double beat, int sink, int lane, float pitch, float velocity)
        {
        }

        private void RouteStingerEvent(double beat, bool startevent, int stingerOrigin)
        {
        }

        private void RouteAudioEnd()
        {
        }

        private void RouteBarBeat(double offset, int bar, int beatIndex)
        {
        }

        #endregion
    }
    
    [Flags]
    public enum LogLevel
    {
        Disabled = 0,
        Log      = 1 << 0,
        Warning  = 1 << 1,
        Error    = 1 << 2,
    }

#if UNITY_EDITOR
    [CustomEditor(typeof(ReactionalEngine))]
    public class ReactionalEngineEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            var engine = (ReactionalEngine)target;
            DrawDefaultInspector();
            var originalValue = engine._logLevel;
            if (ReactionalEngine.LogLevel == originalValue) { return; }
            ReactionalEngine.LogLevel = engine._logLevel;
            EditorUtility.SetDirty(engine);
        }
    }
#endif
}
